
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '9D656719E5E232B729C33632F8EA2010'
    
_lr_action_items = {'LABEL':([0,5,11,17,],[3,8,16,23,]),'OPCODE':([0,],[5,]),'NEWLINE':([0,6,7,8,9,14,15,16,21,22,23,],[4,10,12,13,-11,18,19,20,24,25,26,]),'$end':([1,2,4,10,12,13,18,19,20,24,25,26,],[0,-1,-12,-2,-10,-9,-4,-6,-7,-3,-5,-8,]),'COLUMN':([3,],[6,]),'REGISTER':([5,11,17,],[9,9,9,]),'COMMA':([7,9,14,],[11,-11,17,]),'IMMEDIATE':([11,17,],[15,22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement':([0,],[2,]),'register':([5,11,17,],[7,14,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement','program',1,'p_program_statement','parser.py',40),
  ('program -> LABEL COLUMN NEWLINE','program',3,'p_program_label','parser.py',48),
  ('statement -> OPCODE register COMMA register COMMA register NEWLINE','statement',7,'p_statement_R','parser.py',60),
  ('statement -> OPCODE register COMMA register NEWLINE','statement',5,'p_statement_C','parser.py',74),
  ('statement -> OPCODE register COMMA register COMMA IMMEDIATE NEWLINE','statement',7,'p_statement_I_S_JALR','parser.py',88),
  ('statement -> OPCODE register COMMA IMMEDIATE NEWLINE','statement',5,'p_statement_U','parser.py',133),
  ('statement -> OPCODE register COMMA LABEL NEWLINE','statement',5,'p_statement_UJ_LABEL','parser.py',153),
  ('statement -> OPCODE register COMMA register COMMA LABEL NEWLINE','statement',7,'p_statement_B','parser.py',169),
  ('statement -> OPCODE LABEL NEWLINE','statement',3,'p_statement_J1','parser.py',184),
  ('statement -> OPCODE register NEWLINE','statement',3,'p_statement_J2','parser.py',196),
  ('register -> REGISTER','register',1,'p_register','parser.py',208),
  ('statement -> NEWLINE','statement',1,'p_statement_none','parser.py',220),
]
